server:
  port: 4004

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            ##
            ## PATIENT-SERVICE
            - id: patient-service-route
              uri: http://patient-service:4000
              predicates:
                - Path=/api/patient/**
              filters:
                - StripPrefix=1

            - id: api-docs-patient-route
              uri: http://patient-service:4000
              predicates:
                - Path=/api-docs/patient
              filters:
                - RewritePath=/api-docs/patient,/v3/api-docs